### ISSUE TITLE
Java.Lang.OutOfMemoryError on Android 4.2.2

### ISSUE THREAD

**Issue by jruetas** [mattleibow/square-bindings#15]
I am running the following code on Android 4.2.2 and receiving a Java.Lang.OutOfMemoryError exception when the response body is large:

# Code

            string responseBody = null;
            OkHttpClient client = null;
            Request request = null;
            Response response = null;

            try
            {
                // Create the client
                client = new OkHttpClient().NewBuilder()
                             .ConnectTimeout(TIME_OUT, TimeUnit.Seconds)
                             .ReadTimeout(TIME_OUT, TimeUnit.Seconds)
                             .WriteTimeout(TIME_OUT, TimeUnit.Seconds)
                             .Build();

                // Create the request
                request = new Request.Builder()
				  .Url(url)
				  .Headers(headersBuilder.Build())
				  .Build();

                // Synchronous call
                response = await client.NewCall(request).ExecuteAsync();

                // Returns the response as a string
                responseBody = await response.Body().StringAsync();
            }
            finally
            {
                // Dispose and clear client
                client.Dispose();
                client = null;

                // Dispose and clear request
                request.Dispose();
                request = null;

                // Dispose and clear response
                response.Dispose();
                response = null;
            }

# Exception

12-15 14:53:11.084 D/dalvikvm(30082): GC_CONCURRENT freed 299K, 20% free 13667K/16976K, paused 2ms+2ms, total 25ms
12-15 14:53:11.084 D/dalvikvm(30082): WAIT_FOR_CONCURRENT_GC blocked 18ms
12-15 14:53:11.144 D/dalvikvm(30082): GC_FOR_ALLOC freed 21K, 13% free 14922K/16976K, paused 15ms, total 15ms
12-15 14:53:11.164 D/dalvikvm(30082): GC_FOR_ALLOC freed <1K, 12% free 15107K/17144K, paused 15ms, total 15ms
12-15 14:53:11.194 D/dalvikvm(30082): GC_FOR_ALLOC freed 8K, 12% free 15357K/17396K, paused 20ms, total 20ms
12-15 14:53:11.234 D/dalvikvm(30082): GC_FOR_ALLOC freed <1K, 12% free 15704K/17732K, paused 20ms, total 20ms
12-15 14:53:11.274 D/dalvikvm(30082): GC_FOR_ALLOC freed 17K, 12% free 16147K/18188K, paused 16ms, total 16ms
12-15 14:53:11.314 D/dalvikvm(30082): GC_FOR_ALLOC freed <1K, 11% free 16760K/18788K, paused 16ms, total 16ms
12-15 14:53:11.374 D/dalvikvm(30082): GC_FOR_ALLOC freed 9K, 11% free 17574K/19604K, paused 24ms, total 24ms
12-15 14:53:11.444 D/dalvikvm(30082): GC_FOR_ALLOC freed 9K, 10% free 18663K/20684K, paused 18ms, total 18ms
12-15 14:53:11.514 D/dalvikvm(30082): GC_FOR_ALLOC freed 34K, 10% free 20098K/22136K, paused 16ms, total 16ms
12-15 14:53:11.624 D/dalvikvm(30082): GC_FOR_ALLOC freed 43K, 9% free 22017K/24056K, paused 20ms, total 20ms
12-15 14:53:11.764 D/dalvikvm(30082): GC_FOR_ALLOC freed 36K, 8% free 24589K/26612K, paused 19ms, total 19ms
12-15 14:53:11.954 D/dalvikvm(30082): GC_FOR_ALLOC freed 54K, 7% free 28024K/30044K, paused 19ms, total 19ms
12-15 14:53:12.245 D/dalvikvm(30082): GC_FOR_ALLOC freed 48K, 6% free 32628K/34616K, paused 22ms, total 22ms
12-15 14:53:12.665 D/dalvikvm(30082): GC_FOR_ALLOC freed 91K, 5% free 38764K/40760K, paused 23ms, total 23ms
12-15 14:53:13.095 D/dalvikvm(30082): GC_FOR_ALLOC freed 116K, 5% free 45101K/47096K, paused 24ms, total 24ms
12-15 14:53:13.366 D/dalvikvm(30082): GC_FOR_ALLOC freed 39K, 4% free 48850K/50756K, paused 26ms, total 26ms
12-15 14:53:13.486 I/dalvikvm-heap(30082): Grow heap (frag case) to 83.402MB for 36765198-byte allocation
12-15 14:53:13.526 D/dalvikvm(30082): GC_CONCURRENT freed 36121K, 44% free 48632K/86660K, paused 2ms+4ms, total 42ms
12-15 14:53:13.526 D/dalvikvm(30082): WAIT_FOR_CONCURRENT_GC blocked 17ms
12-15 14:53:13.836 I/dalvikvm-heap(30082): Grow heap (frag case) to 118.250MB for 73530380-byte allocation
12-15 14:53:14.106 D/dalvikvm(30082): JIT unchain all for threadid=21
12-15 14:53:14.377 D/dalvikvm(30082): GC_CONCURRENT freed 16K, 25% free 120423K/158468K, paused 6ms+511ms, total 545ms
12-15 14:53:14.487 D/dalvikvm(30082): GC_FOR_ALLOC freed 0K, 25% free 120423K/158468K, paused 28ms, total 28ms
12-15 14:53:14.487 I/dalvikvm-heap(30082): Forcing collection of SoftReferences for 73530376-byte allocation
12-15 14:53:14.517 D/dalvikvm(30082): GC_BEFORE_OOM freed <1K, 25% free 120422K/158468K, paused 28ms, total 28ms
12-15 14:53:14.517 E/dalvikvm-heap(30082): Out of memory on a 73530376-byte allocation.
12-15 14:53:14.517 I/dalvikvm(30082): "Thread-460" prio=5 tid=21 RUNNABLE
12-15 14:53:14.517 I/dalvikvm(30082):   | group="main" sCount=0 dsCount=0 obj=0x427d9228 self=0x7cbfe7a0
12-15 14:53:14.517 I/dalvikvm(30082):   | sysTid=30198 nice=0 sched=0/0 cgrp=apps handle=2096602616
12-15 14:53:14.517 I/dalvikvm(30082):   | state=R schedstat=( 0 0 0 ) utm=645 stm=104 core=1
12-15 14:53:14.517 I/dalvikvm(30082):   at java.lang.String.<init>(String.java:~354)
12-15 14:53:14.517 I/dalvikvm(30082):   at java.lang.String.<init>(String.java:393)
12-15 14:53:14.517 I/dalvikvm(30082):   at okio.Buffer.readString(Buffer.java:620)
12-15 14:53:14.527 I/dalvikvm(30082):   at okio.Buffer.readString(Buffer.java:603)
12-15 14:53:14.527 I/dalvikvm(30082):   at okio.RealBufferedSource.readString(RealBufferedSource.java:191)
12-15 14:53:14.527 I/dalvikvm(30082):   at okhttp3.ResponseBody.string(ResponseBody.java:175)
12-15 14:53:14.527 I/dalvikvm(30082):   at dalvik.system.NativeStart.run(Native Method)
12-15 14:53:14.527 I/dalvikvm(30082): 
12-15 14:53:14.587 D/Mono    (30082): DllImport searching in: '__Internal' ('(null)').
12-15 14:53:14.587 D/Mono    (30082): Searching for 'java_interop_jnienv_call_static_int_method_a'.
12-15 14:53:14.587 D/Mono    (30082): Probing 'java_interop_jnienv_call_static_int_method_a'.
12-15 14:53:14.587 D/Mono    (30082): Found as 'java_interop_jnienv_call_static_int_method_a'.
**12-15 14:53:14.587 E/AM7Client(30082): Exception of type 'Java.Lang.OutOfMemoryError' was thrown.**
12-15 14:53:15.348 D/dalvikvm(30082): GC_EXPLICIT freed 107738K, 75% free 12695K/50748K, paused 2ms+5ms, total 90ms
12-15 14:53:15.348 D/Mono    (30082): GC_TAR_BRIDGE bridges 43 objects 73 opaque 50 colors 43 colors-bridged 43 colors-visible 43 xref 5 cache-hit 0 cache-semihit 0 cache-miss 0 setup 0.12ms tarjan 0.06ms scc-setup 0.18ms gather-xref 0.00ms xref-setup 0.06ms cleanup 0.06ms
12-15 14:53:15.348 D/Mono    (30082): GC_BRIDGE: Complete, was running for 91.34ms
12-15 14:53:15.348 D/Mono    (30082): GC_MINOR: (Nursery full) time 5.16ms, stw 6.50ms promoted 221K major size: 1472K in use: 756K los size: 1024K in use: 443K
12-15 14:53:15.488 D/Mono    (30082): DllImport attempting to load: '__Internal'.
12-15 14:53:15.488 D/Mono    (30082): DllImport loaded library '(null)'.
12-15 14:53:15.488 D/Mono    (30082): DllImport searching in: '__Internal' ('(null)').
12-15 14:53:15.488 D/Mono    (30082): Searching for 'monodroid_get_system_property'.
12-15 14:53:15.488 D/Mono    (30082): Probing 'monodroid_get_system_property'.
12-15 14:53:15.488 D/Mono    (30082): Found as 'monodroid_get_system_property'.
12-15 14:53:15.488 D/Mono    (30082): DllImport searching in: '__Internal' ('(null)').
12-15 14:53:15.488 D/Mono    (30082): Searching for 'monodroid_free'.
12-15 14:53:15.488 D/Mono    (30082): Probing 'monodroid_free'.
12-15 14:53:15.488 D/Mono    (30082): Found as 'monodroid_free'.

# On Android 5.1+

I must say that when I run the same code on Android 5.1+ it works fine.  The only difference is I use 

                responseBody = await response.Body().String();

instead of

                responseBody = await response.Body().StringAsync();

since I cannot run network code on the main thread since I will receive the NetworkOnMainThreadException exception.

**Comment by dehghani-mehdi** [comment]
Can you test same code using Java (not xamarin)?
For better support maybe you should try to open the issue on main/Java repo, not here.
