### ISSUE TITLE
exception on device : Unable to get provider com.squareup.picasso.PicassoProvider

### ISSUE THREAD

**Issue by jonathanantoine** [mattleibow/square-bindings#67]
Hello,

I have this issue when deploying on device, any idea ? 

Thanks !

```
java.lang.RuntimeException: Unable to get provider com.squareup.picasso.PicassoProvider: java.lang.InstantiationException: java.lang.Class<com.squareup.picasso.PicassoProvider> cannot be instantiated
	at android.app.ActivityThread.installProvider(ActivityThread.java:7152)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6630)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6525)
	at android.app.ActivityThread.access$1400(ActivityThread.java:220)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1883)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7520)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: java.lang.InstantiationException: java.lang.Class<com.squareup.picasso.PicassoProvider> cannot be instantiated
	at java.lang.Class.newInstance(Native Method)
	at android.app.AppComponentFactory.instantiateProvider(AppComponentFactory.java:147)
	at androidx.core.app.CoreComponentFactory.instantiateProvider(Unknown Source:0)
	at android.app.ActivityThread.installProvider(ActivityThread.java:7136)
	... 10 more
```

**Comment by jonathanantoine** [comment]
Hello again,

This was a R8/Proguard related issue. I fixed it by adding this line : 
```
-keep class com.squareup.picasso.PicassoProvider { *; <init>(...); }
```
